stages:
  - build
  - test
  - push
  - deploy

build_job:
  stage: build
  script:
    - docker build -t netflix-app .
  tags:
    - dev  

test_job:
  stage: test
  script:
    - echo "Running tests"
  tags:
    - dev

push_job:
  stage: push
  script:
    - docker push netflix-app
  tags:
    - dev

deploy_job:
  stage: deploy
  script:
    - docker run -p 3000:3000 netflix-app
  tags:
    - dev
