stages:
  - build
  - test
  - push
  - deploy

build_job:
  stage: build
  script:
   - docker build -t netflix-app .
  tags:
    - prod

test_job:
  stage: test
  script:
   - echo "this is test stage"
  tags:
    - prod

push_job:
  stage: push
  script:
   - echo "this is push stage using command <docker push netflix-app>"
  tags:
    - prod

deploy_job:
  stage: deploy
  script:
   - docker run -d -p 3000:3000 --name netflix netflix-app
  tags:
    - prod
