kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: letsencrypt-prod  
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sauravgarg5922@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

