apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: ott
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: netflix
        image: saurav547/netflix-app
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi" # Minimum memory the pod will request
            cpu: "200m"
          limits:
            memory: "512Mi" # Maximum memory the pod can use
            cpu: "500m"
